export const serviceCards = [
  {
    slug: 'drain-cleaning',
    icon: 'waves',
    title: 'Drain Cleaning',
    copy: 'Drain cleaning for clogged sinks, tubs, toilets, kitchen drains, bathroom drains, and main-line backups that need fast attention.',
    bullets: ['Clog removal', 'Slow drain diagnostics', 'Kitchen, bath, and main drains'],
    category: 'Plumbing',
  },
  {
    slug: 'ac-repair',
    icon: 'snowflake',
    title: 'AC Repair',
    copy: 'AC repair for weak airflow, warm air, short cycling, unusual noises, and cooling systems that stop keeping up.',
    bullets: ['AC diagnostics', 'Cooling repairs', 'System troubleshooting'],
    category: 'HVAC',
  },
  {
    slug: 'ac-replacement',
    icon: 'refresh-cw',
    title: 'AC Replacement',
    copy: 'AC replacement planning for older, inefficient, or unreliable systems when repair is no longer the best long-term choice.',
    bullets: ['Replacement options', 'Efficiency guidance', 'Comfort planning'],
    category: 'HVAC',
  },
  {
    slug: 'ac-installation',
    icon: 'settings',
    title: 'AC Installation',
    copy: 'AC installation for new systems, correctly sized equipment, clean setup, and dependable cooling performance.',
    bullets: ['New AC installs', 'System sizing', 'Clean installation'],
    category: 'HVAC',
  },
  {
    slug: 'furnace-repair',
    icon: 'flame',
    title: 'Furnace Repair',
    copy: 'Furnace repair for unreliable heat, ignition issues, airflow problems, unusual smells, and systems that will not start correctly.',
    bullets: ['Furnace diagnostics', 'Heating repairs', 'Safety checks'],
    category: 'HVAC',
  },
  {
    slug: 'furnace-replacement',
    icon: 'replace',
    title: 'Furnace Replacement',
    copy: 'Furnace replacement guidance for older, inefficient, or unreliable heating systems that need a better long-term solution.',
    bullets: ['Replacement options', 'Efficiency guidance', 'Comfort planning'],
    category: 'HVAC',
  },
  {
    slug: 'insulation',
    icon: 'home',
    title: 'Insulation',
    copy: 'Insulation service to reduce heat gain, improve home comfort, and help your heating and cooling system perform more efficiently.',
    bullets: ['Comfort improvements', 'Efficiency support', 'Home performance guidance'],
    category: 'HVAC',
  },
  {
    slug: 'air-duct-cleaning',
    icon: 'wind',
    title: 'Air Duct Cleaning',
    copy: 'Air duct cleaning for dusty vents, airflow concerns, indoor air quality issues, and cleaner whole-home comfort.',
    bullets: ['Duct cleaning', 'Airflow support', 'Cleaner comfort'],
    category: 'HVAC',
  },
  {
    slug: 'water-heaters',
    icon: 'droplets',
    title: 'Water Heaters',
    copy: 'Water heater repairs, replacements, and hot water troubleshooting for tank and tankless systems.',
    bullets: ['Tank and tankless installs', 'No-hot-water diagnostics', 'Flush and maintenance service'],
    category: 'Plumbing',
  },
  {
    slug: 'heating',
    icon: 'flame',
    title: 'Heating Service',
    copy: 'Heating service and repair support for furnaces, unreliable heat, airflow problems, and replacement planning.',
    bullets: ['Heating diagnostics', 'Furnace repairs', 'Replacement guidance'],
    category: 'HVAC',
  },
  {
    slug: 'hvac',
    icon: 'thermometer-sun',
    title: 'HVAC Service',
    copy: 'Heating and cooling diagnostics, repairs, tune-ups, and comfort troubleshooting for year-round performance.',
    bullets: ['Heating and cooling diagnostics', 'AC and heater repairs', 'Seasonal tune-ups'],
    category: 'HVAC',
  },
];

export const servicesBySlug = Object.fromEntries(serviceCards.map((service) => [service.slug, service]));
